### ISSUE TITLE
Tool doesn't switch to the Mekanism Configurator while looking at a pipe from the mod, but it does when looking at a machine.

### ISSUE THREAD

**Issue by Amperthorpe** [VazkiiMods/Morph-o-Tool#15]

**Comment by Vazkii** [comment]
Are the pipes from another mod? If so, add an alias.

**Comment by Alleluid** [comment]
They are not from a different mod, that's what's strange about it.

**Comment by Vazkii** [comment]
Are you sure? Some mods split their features into modules.

**Comment by Alleluid** [comment]
WAILA shows the same mod name "Mekanism" and the mod is one .jar file. Mekanism used to be split up into modules, but even so I'm pretty sure the pipes and machines were always in the same main mod. If they are split up how would I find the names of the other modules to add them as an alias?

**Comment by Vazkii** [comment]
Look at your mods list, see if there's any modules there. I guess we could ask @aidancbrady as well.

**Comment by TonRZN** [comment]
@Vazkii @Alleluid The pipes when placed on the ground turn into MCMultiPart blocks so the Morph-o-Tool doesn't change to the Mekanism Configurator

**Comment by amadornes** [comment]
You'll need to look at the RayTraceResult, check if it's a PartMOP and if it is, get partHit from it. That should give you the object you need to do the mod lookup for :)

**Comment by Uraneptus** [comment]
I will close thos because it's very old! If this issue is still relevant, please open a new issue.
