### ISSUE TITLE
Can't use ore dictionary dyes in recipe for Morph-O-Tool

### ISSUE THREAD

**Issue by drinfernoo** [VazkiiMods/Morph-o-Tool#25]
For example, the floral dyes from Botania, or the dye powder from Substratum.

**Comment by PapiDimmi** [comment]
I was going to create this issue, too.

This is quite annoying; you _have_ to find a cactus to make this thing, and you can’t use any other green dye. I don’t get why Morph-O-Tool doesn’t use Ore Dictionary.

**Comment by Uraneptus** [comment]
If this is still relevant in the newest version, please open a new issue
