### ISSUE TITLE
Refined Storage wrench destroys morph-o-tool

### ISSUE THREAD

**Issue by werwerwsx** [VazkiiMods/Morph-o-Tool#31]
Adding RS wrench to morph-o-tool then switching between rotation and configuration mode turns it into a regular RS wrench and seems to completely remove the morph-o-tool. Found in version 1.0.0 of the Direwolf20 1.10 pack.

![1](https://cloud.githubusercontent.com/assets/22715665/20612348/950077f2-b27e-11e6-80ec-616a2c7d3325.png)
![2](https://cloud.githubusercontent.com/assets/22715665/20612349/950554ac-b27e-11e6-9ace-815f76e14c72.png)
![3](https://cloud.githubusercontent.com/assets/22715665/20612350/950af358-b27e-11e6-9e10-965e1ca43543.png)
![4](https://cloud.githubusercontent.com/assets/22715665/20612351/9510f550-b27e-11e6-9850-30e487d67982.png)

**Comment by Uraneptus** [comment]
If this is still relevant in the newest version, please open a new issue
