### ISSUE TITLE
Not Working With SCM Screwdriver

### ISSUE THREAD

**Issue by simpson409** [VazkiiMods/Morph-o-Tool#32]

**Comment by werwerwsx** [comment]
The screwdriver from SCM takes damage which I believe disqualifies a tool from being added to Morph, since keeping track of damage/removing the tool when it broke either isn't coded yet or Vazkii isn't planning on coding in.

**Comment by Vazkii** [comment]
You are completely wrong. This has to do with SCM not having its own blocks
but rather having them as McMultipart pieces.

**Comment by werwerwsx** [comment]
Ah, my apologies.

**Comment by gmoff01** [comment]
Does the reason mentioned above mean that this can never work, or just that it will need later implementation?

**Comment by gmoff01** [comment]
Or maybe a config alias for the micropart system?

**Comment by PapiDimmi** [comment]
Dupe of #27 and #15.

**Comment by Uraneptus** [comment]
If this is still relevant in the newest version, please open a new issue
