### ISSUE TITLE
The morphing tool does not work with Super Circuit Maker

### ISSUE THREAD

**Issue by ghost** [VazkiiMods/Morph-o-Tool#39]
I can add the screwdriver to the morphing tool, but it doesn’t switch to the screwdriver when looking at a Super Circuit Maker circuit.

I _know_ that this is a duplicate of #32, #27, and #15, but it was reported eight and a half months ago and still hasn’t been fixed, even though @Vazkii has acknowledged this.

@Vazkii, can you _please_ add MCMultiPart compatibility to Morph-o-Tool? That would be amazing.

**Comment by Uraneptus** [comment]
If this is still relevant in the newest version, please open a new issue
