### ISSUE TITLE
No recognition of TE machines in DW20 modpack for MC1.10.2

### ISSUE THREAD

**Issue by BoboSims** [VazkiiMods/Morph-o-Tool#41]
I'm running the latest version of DW20's modpack for 1.10.2 with:

Morph-o-Tool-1.0-12
ThermalExpansion-1.10.2-5.0.4.90-universal (updated)
ThermalFoundation-1.10.2-2.0.5.81-universal (updated)

Morph-o-Tool does *not* mimic anything (including the Crescent Hammer) when pointing at any Thermal Expansion and Thermal Foundation blocks/machines. When mousing over the Tool and pressing Shift, the tool tip mentions that the Crescent Hammer is linked to Thermal Foundation, so it *should* work, right?

The config shows only *one* TE-related alias, binding Thermal Dynamics to Thermal Expansion. But Thermal Foundation is never mentioned, even though THAT is the pack named in the tool tip.

So - seeing as how the default setting didn't work anyway - I've tried changing the aliases. No joy, though.

Inspired by this issue, I went looking for a way to extract the Crescent Hammer from the tool again. After all, if the tool doesn't mimic the Crescent Hammer, I'll need to use the Hammer separately. Sneak-dropping only works for the tools that show up. If I point at Botania's Petal Apothecary, the Wand of the Forest shows up, and I can drop it. But if I point at any TE/TF devices, the Crescent Hammer is *not* shown, so it cannot be dropped, either!

Thank you for your time.

**Comment by Hazmatik** [comment]
Had same issue on FTB Beyond with the TE machines but I made a block of tin from Thermal Foundation and when I looked at it, the crescent hammer displayed and was able to sneak drop it

**Comment by BoboSims** [comment]
Ah, so THAT at least fixes dropping the tool. Thanks for pointing that out, Hazmatik.

**Comment by BoboSims** [comment]
Ah, so that at least allows me to drop the tool. Thanks for pointing it out, Hazmatik! :)

**Comment by zrieprakis** [comment]
@BoboSims - If you haven't gotten this working yet, I'd just added these lines to my server config under the "Mod aliases" heading.  Should work client-side for single player, too:

ThermalDynamics=ThermalFoundation
ThermalExpansion=ThermalFoundation

Hope that works for you.

**Comment by BoboSims** [comment]
@zrieprakis - I would need to check, but Thermal Foundation is one of the things that isn't recognized. So I don't think that aliasing the others to it would be helpful at all. At the very least, it seems counter intuitive and is most likely counter productive as well. But as said, I would need to test it before I can speak with any certainty.
