### ISSUE TITLE
2 tools for 1 mod ?

### ISSUE THREAD

**Issue by flapili** [VazkiiMods/Morph-o-Tool#44]
Hi, how i can switch if i have 2 tool of the same  mod ? for exemple network reader & configurator ( mekanism).
What append if i have 2 tool in my morph'o toll for 1 mod ? he switch in first added tool ?

EDIT :  https://github.com/Vazkii/Morph-o-Tool/pull/33
Not work in V 1.0-12

**Comment by MusicMaestro123** [comment]
Shift + Scroll up or down
