### ISSUE TITLE
Renamed Morph-O-Tools lose their name when they transform

### ISSUE THREAD

**Issue by TheDeviantCrafter** [VazkiiMods/Morph-o-Tool#49]
In the pack I'm working on, I'm including a Morph-O-Tool with every wrench, hammer and screwdriver in the game already included. I've added a recipe and forced it to appear in JEI. I've also configured it to work smoothly with all of the mods in my pack.

The wrench is renamed to the Universal Wrench. When the player turns it into a modded wrench and back, this name is lost.

**Comment by Uraneptus** [comment]
If this is still relevant in the newest version, please open a new issue
