### ISSUE TITLE
multiplayer - wrench use causes flickering hand

### ISSUE THREAD

**Issue by zeronacer** [VazkiiMods/Morph-o-Tool#50]
I have mod version 1.2.16 installed on my Direwolf20 server (newest modpack release) with two players.
When I use the morph-o-tool or if it switches forms, the hand of the other player updates as well (the animation of the hand or item rising from the bottom of the screen)

**Comment by MoreThanHidden** [comment]
Duplicate issue to #30 and fixed in PR
