### ISSUE TITLE
LordCraft Translocation Marker breaks Morphing Tool

### ISSUE THREAD

**Issue by swoolcock** [VazkiiMods/Morph-o-Tool#52]
Merging the LordCraft Translocation Marker with the Morphing Tool and then using it will destroy all Morphing Tool-related data in the item, reverting it to a regular Translocation Marker.

Probably not a Morph-o-Tool problem, but maybe worth blacklisting it by default.

**Comment by Uraneptus** [comment]
If this is still relevant in the newest version, please open a new issue
