### ISSUE TITLE
[1.15.2] Beds get cut in half

### ISSUE THREAD

**Issue by ghost** [VazkiiMods/Morph-o-Tool#58]
Beds get cut in half. To reproduce this: just place a bed.

Versions used:
AutoRegLib-1.5-40.jar
Morph-o-Tool-1.3-23.jar
Forge 1.15.2 31.1.0 as well as 31.1.63

**Comment by kd8lvt** [comment]
It appears any block that 'connects' with other blocks (eg. chests and doors) also have problems. I've found that having two or more of the item in your hand solves the issue. I think this error message may be related:
[https://hastebin.com/uyecetecim.cs](https://hastebin.com/uyecetecim.cs)

**Comment by MoreThanHidden** [comment]
Yeah #57 probably fixes this.
