### ISSUE TITLE
Tools break Morph-o-Tool if they are used as weapons

### ISSUE THREAD

**Issue by DoomRater** [VazkiiMods/Morph-o-Tool#62]
From what I can tell, in 1.2-21 and onward, the Morph-o-Tool can still break, not returning any item, if the item receives damage from being used as a weapon.  I suspect it also does so when damaged by a crafting recipe, though Immersive Engineering is using its own damage tracking system and is probably an exception that can't be caught anyway.

Is it possible to extend the events to catch uses as weapons?  Mentioning as a new issue since I'm not sure closed issues are ever read.

**Comment by Uraneptus** [comment]
If this is still relevant in the newest version, please open a new issue
