### ISSUE TITLE
crashing when holding shift 

### ISSUE THREAD

**Issue by benbenlaw** [VazkiiMods/Morph-o-Tool#64]
crashing when holding shift hovering over morpho o tool

**Comment by benbenlaw** [comment]
[crash-2021-02-06_11.10.56-client.txt](https://github.com/Vazkii/Morph-o-Tool/files/5936717/crash-2021-02-06_11.10.56-client.txt)

**Comment by Uraneptus** [comment]
If this is still relevant in the newest version, please reopen the issue
