### ISSUE TITLE
unable to put both storage drawers keys inside tool

### ISSUE THREAD

**Issue by benbenlaw** [VazkiiMods/Morph-o-Tool#65]
added both items to the config, it only lets me put in one or the other not both any ideas?

**Comment by Jack-McKalling** [comment]
From the perspective of the tool morphing into the item when looking at blocks from the item's mod, it is understandable that having more than one item in the tool from the same mod would be confusing to the tool. But this is a serious limition.

Is there no way to get around this?

**Comment by Uraneptus** [comment]
If this is still relevant in the newest version, please reopen the issue

**Comment by Uraneptus** [comment]
Great to hear that the key ring works! Could you open a new issue for the naming issue? If you got time a few screenshots would help me too! ^^

**Comment by Jack-McKalling** [comment]
To be fair, the keyring working is not really any different from the keys working too, individually. This issue is about multiple items canceling each other out, so to say. I'll make a new issue later for the keyring though.

**Comment by Jack-McKalling** [comment]
I'll make a separate report shortly, but I just wanted to show this screenshot:
![image](https://github.com/user-attachments/assets/dfbbff8d-7fd9-4f89-bc52-2ce53856d40c)

Having the drawer key in the tool doesn't allow adding the quantify key to it as shown. This is still the case even though there now is a keyring. My suggestion to fix this is to add "keyring" to the "whitelisted names" config by default, and not simply "key". This forces the use of the keyring, which still allows the player to have just a single key on it if they want.

Not adding support for multiple items from the same mod should be fine from the perspective of Storage Drawers, now with the benefit of the keyring. As long as the keyring gets default support.

**Comment by Uraneptus** [comment]
I'm planning on doing that! I just didn't even know the ring existed until you mentioned it

**Comment by Jack-McKalling** [comment]
I suggested creating it recently, and provided with a design.
Great, thanks!

**Comment by Uraneptus** [comment]
Ohh okay, cool!
