### ISSUE TITLE
adding keys 

### ISSUE THREAD

**Issue by benbenlaw** [VazkiiMods/Morph-o-Tool#67]
adding storage drawers keys to the tool in config but wont take both together only takes either one

**Comment by Jack-McKalling** [comment]
In other words the tool cannot accept more than one item from the same mod at a time.

From the perspective of the tool morphing into the item when looking at blocks from the item's mod, it is understandable that having more than one item in the tool for the same mod would be confusing to the tool. E.g. if you had both the drawer key and quantify key in the tool and you looked at a drawer, what key should it then morph into if it has both? But this is a serious limition.

**Comment by Jack-McKalling** [comment]
Actually, duplicates #65. You already reported this before

**Comment by Uraneptus** [comment]
If this is still relevant, please open a new issue for the newest version
