### ISSUE TITLE
unmorphed morph-o-tool should act as a generic wrench similar to thermal's hammer

### ISSUE THREAD

**Issue by LemonShaped** [VazkiiMods/Morph-o-Tool#68]

**Comment by Vazkii** [comment]
The unmorphed tool uses the forge rotation methods, so if any mods aren't
accepting them, that's a bug on their side

**Comment by LemonShaped** [comment]
for me it doesnt work on anything, even rotating vanilla blocks

**Comment by Uraneptus** [comment]
It works again in newer versions
