### ISSUE TITLE
[Suggestion] Morph-o-Armor

### ISSUE THREAD

**Issue by Yusunoha** [VazkiiMods/Morph-o-Tool#74]
the morph-o-tool is really helpful with all the different mods and their tools, as you don't have to use up all those inventory spaces for all the different kinds of wrenches and tools. but quite a few mods nowadays also add their own kinds of armor to the game, and they usually have functionality besides just protection.

would it perhaps be possible to create a morph-o-tool, but for armor? a Morph-o-Armor tool.
I've tried thinking of how the tool would be used, and I was thinking of the Morph-o-Armor tool to be an item.

to add an armor set to the tool, you place down an armor stand and equip it with the armor set you want to add. you then shift-right click the armor stand with the tool, and the armor stand with the armor set gets transferred to the tool.

the tool would be a curios item, so you'd need to equip it in a curios slot. by pressing a hotkey, you'll be able to swap between the different saved armor sets. if you want to edit an armor set (for example by changing a helmet) you select the armor set, take out the tool out of your curios slot, and shift-right click the tool on a block, and the armor stand with the armor set gets taken out of the tool. you'd now be able to change the armor set, and transfer it back into the tool.

while you've the tool in your curios slot, your normal armor slots are disabled. the armor you were wearing are still in the armor slots, but they don't add any protection or functionality to your character, and you can only unequip them.

**Comment by Uraneptus** [comment]
This suggestion could be reconsidered in some way in the far future, but is not planned as of rn.
