### ISSUE TITLE
[BUG] Buildcraft wrench not working on Iron Transport Pipe

### ISSUE THREAD

**Issue by xdjzack** [VazkiiMods/Morph-o-Tool#85]
Iron Transport Pipe is a pipe that only has one exit, and the wrench changes the direction.

Using the buildcraft wrench through Morph-A-Tool does not work on the Iron Transport Pipe, but it does work on the redstone engine.

Thats all I have testet so far.

Minecraft 1.12.2
buildcraft-all-7.99.24.8.jar
Morph-o-Tool-1.2-21.jar

![Not working](https://github.com/user-attachments/assets/b7a8b0e7-3192-4948-83f9-f25915710efe)
![Working](https://github.com/user-attachments/assets/755dfad8-62fe-478d-95ed-d92104b16989)

**Comment by Uraneptus** [comment]
Sorry, but that minecraft version is not supported anymore!
